### ISSUE TITLE
[FIRRTL] Add Names to Side Effecting Statements, Make them Annotatable

### ISSUE THREAD

**Issue by seldridge** [llvm/circt#1313]
Upstream FIRRTL added names to stop, printf, and verification statements (assert, assume, cover) in https://github.com/chipsalliance/firrtl/pull/2057.  

Support for annotating FIRRTL IR verification statements is being added to the Chisel in 3.5.0 (this is unreleased) in https://github.com/chipsalliance/chisel3/pull/1968.

Update the ODS representation of FIRRTL dialect to hold this name (which should be optional?). Update the annotation parsing logic to attach annotations to these side effecting statements.

**Comment by ekiwi** [comment]
> Update the ODS representation of FIRRTL dialect to hold this name (which should be optional?)

I mostly made it optional for backwards compatibility reasons. Imho for the C++ firrtl compiler, it might make sense to just auto-generate unique names right after the parser in order to simplify the IR. For the Scala firrtl compiler we have to deal with IR nodes that don't come from the parser. The Scala firrtl compiler has `firrtl.transforms.EnsureNamedStatements` for transformations and backends that require named statements and I could see that becoming an "on by default" transform.

**Comment by lattner** [comment]
If this is a string name, please don't make it an optional attribute, please just use "empty string" to mean missing.  This avoids the tristate problem where we have "present" "absent" and "empty" and have to rationalize that.

**Comment by ekiwi** [comment]
> If this is a string name, please don't make it an optional attribute, please just use "empty string" to mean missing. This avoids the tristate problem where we have "present" "absent" and "empty" and have to rationalize that.

That is the implementation we chose for the Scala firrtl compiler. We just need to ensure that if a pass wants to use the name it needs to first verify that the String is non-empty. There are also now some special cases in our identifier name checking code that makes it so that more than one statement is allowed to be named `""`.
