### ISSUE TITLE
[ExportVerilog] `appendPossiblyAbsolutePath` not found in unified build

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#1933]
In doing a unified build, I'm getting:

```
ld.lld: error: undefined symbol: circt::appendPossiblyAbsolutePath(llvm::SmallVectorImpl<char>&, llvm::Twine const&)
>>> referenced by ExportVerilog.cpp:3597 (/home/jodemme/circt/lib/Conversion/ExportVerilog/ExportVerilog.cpp:3597)
>>>               ExportVerilog.cpp.o:((anonymous namespace)::SharedEmitterState::gatherFiles(bool)) in archive lib/libCIRCTExportVerilog.a
>>> referenced by ExportVerilog.cpp:3867 (/home/jodemme/circt/lib/Conversion/ExportVerilog/ExportVerilog.cpp:3867)
>>>               ExportVerilog.cpp.o:(createSplitOutputFile(mlir::Identifier, (anonymous namespace)::FileInfo&, llvm::StringRef, (anonymous namespace)::SharedEmitterState&)) in archive lib/libCIRCTExportVerilog.a
>>> referenced by BlackBoxReader.cpp:230 (/home/jodemme/circt/lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp:230)
>>>               BlackBoxReader.cpp.o:((anonymous namespace)::BlackBoxReaderPass::runOnAnnotation(mlir::Operation*, circt::firrtl::Annotation, mlir::OpBuilder&)) in archive lib/libCIRCTFIRRTLTransforms.a
>>> referenced 1 more times
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Introduced by d8d7153320640d703a503736b144069810c419b4. Likely missing a cmake dep.

**Comment by richardxia** [comment]
I was running into weird issues while developing this locally that I "fixed" by `touch`ing `lib/Support/CMakeLists.txt`, since it seemed like the issue was that cmake didn't understand that it needed to rebuild the CIRCTSupport library. I'm guessing this is due to the [glob pattern](https://github.com/llvm/circt/blob/d8d7153320640d703a503736b144069810c419b4/lib/Support/CMakeLists.txt#L6) in in that file.

I can just replace the glob with the individually listed files, which is what many of our other CMakeLists.txt files do.  I'm not very familiar with cmake, so I'm not sure what the best practices are, but if it'll help unbreak people's local development environments without forcing everyone to `touch` that file, it's probably a step forward.

**Comment by teqdruid** [comment]
Thanks for the speedy response!

**Comment by richardxia** [comment]
No problem, and I also pushed https://github.com/llvm/circt/commit/893f5e912f4bbfbab77dd011e53b9ff5e7b97cd4 directly to `main`, since this is going to affect everyone else as well.
