### ISSUE TITLE
[SystemC] Nightly integration ExportSystemC 'release' mode tests are failing

### ISSUE THREAD

**Issue by teqdruid** [llvm/circt#5236]
https://github.com/llvm/circt/actions/runs/5032040829

**Comment by dtzSiFive** [comment]
Looks like it's only on GCC configurations, and appears to be because `clang-tidy` is being used to check the systemC output which fails due to an unrecognized compiler flag (`-fno-lifetime-dse`, a GCC-only flag).

Perhaps gate these on using clang as CC? Similar failure may happen if clang-tidy and clang versions don't match, but that seems less likely/common.

Or invoke clang-tidy separate from the CIRCT build system's compilation configuration, directly pointing it at the systemc headers it probably needs (?).
