### ISSUE TITLE
[FIRRTL] Parser `< 0` always false

### ISSUE THREAD

**Issue by fabianschuiki** [llvm/circt#825]
I currently see the following warning:
```
../lib/Dialect/FIRRTL/Import/FIRLexer.cpp: In member function ‘circt::firrtl::FIRToken circt::firrtl::FIRLexer::lexInlineAnnotation(const char*)’:
../lib/Dialect/FIRRTL/Import/FIRLexer.cpp:323:17: warning: comparison of unsigned expression in ‘< 0’ is always false [-Wtype-limits]
  323 |       if (depth < 0)
      |           ~~~~~~^~~
```

**Comment by seldridge** [comment]
Ack... My bad. I looked at this check and I don't think it's ever actually possible to trip, even when using a signed type. That method is always called starting from`%[` meaning that the function will exit before you can ever find a `]` that will decrement the depth sufficiently to trip it.  I went ahead and just removed the check instead of switching to a signed type for the `depth`. Thanks for reporting this, @fabianschuiki!
